// <auto-generated />
using System;
using KitApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace KitApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200504103816_AlterBookTable")]
    partial class AlterBookTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("KitApp.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbnailUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InStock")
                        .HasColumnType("int");

                    b.Property<bool>("IsPreferredBook")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PageNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PublicationDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 7,
                            Description = "'Yüzüklerin Efendisi' son yüzyılın en çok okunan yüz kitabı arasında en başta geliyor; bilimkurgu, fantezi, polisiye, best-seller ya da ana akım demeden, tüm edebiyat türleri arasında tartışmasız bir önderliğe sahip. Bir açıdan bakarsanız bir fantezi romanı, başka bir açıdan baktığınızda, insanlık durumu, sorumluluk, iktidar ve savaş üzerine bir roman. Bir yolculuk, bir büyüme öyküsü; fedakârlık ve dostluk üzerine, hırs ve ihanet üzerine bir roman.",
                            Dimensions = "13x20",
                            ImageThumbnailUrl = "~/images/BookThumbnails/lotr1.jpg",
                            ImageUrl = "",
                            InStock = 25,
                            IsPreferredBook = true,
                            Language = "Türkçe",
                            Name = "Yüzüklerin Efendisi - I - Yüzük Kardeşliği",
                            PageNumber = "496",
                            Price = 48.00m,
                            PublicationDate = "2000",
                            Publisher = "Metis Yayıncılık"
                        },
                        new
                        {
                            Id = 2,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 7,
                            Description = "Dünya ikiye bölünmüştür, denir Tolkien'ın yapıtı söz konusu olduğunda: Yüzüklerin Efendisi'ni okumuş olanlar ve okuyacak olanlar. Artık Türkiye'li okur da okumuş olanlar tarafına geçebilecek! 'Yüzüklerin Efendisi' son yüzyılın en çok okunan yüz kitabı arasında en başta geliyor; bilimkurgu, fantezi, polisiye, best-seller yada ana akım demeden, tüm edebiyat türleri arasında tartışmasız bir önderliğe sahip. Bir açıdan bakarsanız bir fantezi romanı, başka bir açıdan baktığınızda, insanlık durumu, sorumluluk, iktidar ve savaş üzerine bir roman. Bir yolculuk, bir büyüme öyküsü; fedakarlık ve dostluk üzerine, hırs ve ihanet üzerine bir roman.Bu ciltte Yüzük kardeşliği dağılıyor. Frodo ve Sam Yüzük'te birlikte Mordor'un kapılarından geçmeye çlaşırken yeni bir yola arkadaşı ediniyorlar. Orklara esir düşen Merry ve Pippin, Orta Dünya'nın en lmeski ırkıyla tanışıyorlar. Aragorn, Gimli ve Legolas ise, Orta Dünya'nın kaderini çizecek büyük savaşların ilkine katılıyorlar... ",
                            Dimensions = "13x20",
                            ImageThumbnailUrl = "~/images/BookThumbnails/lotr2.jpg",
                            ImageUrl = "",
                            InStock = 14,
                            IsPreferredBook = false,
                            Language = "Türkçe",
                            Name = "Yüzüklerin Efendisi - II - İki Kule",
                            PageNumber = "416",
                            Price = 40.50m,
                            PublicationDate = "2014",
                            Publisher = "Metis Yayıncılık"
                        },
                        new
                        {
                            Id = 3,
                            Author = "J.R.R. Tolkien",
                            CategoryId = 7,
                            Description = "Yüzüklerin Efendisi son yüzyılın en çok okunan yüz kitabı arasında en başta geliyor. Türkçe basımının ilk iki kitabı Yüzük Kardeşliği ve İki Kule, bu ilginin evrenselliğini kanıtladı. Polisiye ya da bilimkurgu meraklıları, şiir, roman ve öykü okurları, hep birlikte Frodo, Sam, Merry, Pippin, Aragorn ve Gandalf'ın maceralarını okumaya, 'Orta Dünya'da yaşamaya başladılar.Üçüncü kitap Kralın Dönüşü ile birlikte Yüzüklerin Efendisi tamamlanıyor: Bu kısımda Karanlıklar Efendisi ile Yüzük Kardeşliği, iki cephede karşı karşıya geliyorlar. Frodo ve Sam ellerinde hepsine hükmedecek Tek Yüzük ile Mordor'un içine, karanlığın kalbine doğru bir yolculuk yaparken, diğerleri de karanlığa karşı son cephe olan Gondor'da umutsuz bir savunmaya girişiyorlar...",
                            Dimensions = "13x20",
                            ImageThumbnailUrl = "~/images/BookThumbnails/lotr3.jpg",
                            ImageUrl = "",
                            InStock = 19,
                            IsPreferredBook = false,
                            Language = "Türkçe",
                            Name = "Yüzüklerin Efendisi - III - Kralın Dönüşü",
                            PageNumber = "408",
                            Price = 40.50m,
                            PublicationDate = "2015",
                            Publisher = "Metis Yayıncılık"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Cemal Süreya",
                            CategoryId = 5,
                            Description = "Cemal Süreya, ilk kitabı Üvercinka 1958'de çıktığında, 27 yaşında, ilk şiiri (\"Şarkısı Beyaz\") daha beş yıl önce yayımlanmış genç bir şairdi. Bu kitapla çağcıl Türk şiirinin en çok konuşulan, en çok tartışılan akımlarından İkinci Yeni'nin öncülerinden biri olacağını ne kendisi ne de bir başkası bilebilirdi.",
                            ImageThumbnailUrl = "~/images/BookThumbnails/uvercinka.jpg",
                            ImageUrl = "",
                            InStock = 5,
                            IsPreferredBook = false,
                            Language = "Türkçe",
                            Name = "Üvercinka",
                            PageNumber = "64",
                            Price = 6m,
                            PublicationDate = "2014",
                            Publisher = "Yapı Kredi Yayınları"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Ali Lidar",
                            CategoryId = 5,
                            Description = "Linç Çağı’nda, Şirintepe Parkı’nda, heybende meleğin emanetleri, çölleri ve karlı ovaları aşacak, yangınlara tanık olacaksın, soyut atların gölgesinde soluklanıp, şirk sınırlarını zorlarken, deliydim geçti de geç.Bu yolculukta en çok kendine tanık olacaksın; ayrılık öfke ve keder yoldaşın olacak, müzevirler dünyanı karartacak. Ali Lidar şiirleriyle seni, sana anlatacak.Dünyanın yükü kendisinden ağırsa, tek çare terazinin kefesine bir tutam adalet koymaktır.Aslında Herkes Haklı, anılardan bir kırkyama…",
                            Dimensions = "13.5x21",
                            ImageThumbnailUrl = "~/images/BookThumbnails/aslindaherkeshakli.jpg",
                            ImageUrl = "",
                            InStock = 48,
                            IsPreferredBook = true,
                            Language = "Türkçe",
                            Name = "Aslında Herkes Haklı",
                            PageNumber = "128",
                            Price = 10.22m,
                            PublicationDate = "2018",
                            Publisher = "İthaki Yayınları"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Jean-Christophe Grange",
                            CategoryId = 8,
                            Description = "Kara orman’da son av başladı… ardında hiçbir iz bırakmayan avcı kim? Komiser Niémans,yardımcısı Ivana Bogdović’le Alsace bölgesinde işlenen vahşi bir cinayeti çözmeye gider.Kendi karanlık geçmişlerini de yanlarında götüren iki polis,Kara Orman’da saklanan bir sırrın peşine düşerler.Kızıl Nehirler’in başkahramanı Niémans’ın dönüşünü müjdeleyen Son Av,kökeni Nazi Almanyası’na kadar giden sürprizlerle dolu bir gerilim…",
                            Dimensions = "14x23",
                            ImageThumbnailUrl = "~/images/BookThumbnails/sonav.jpg",
                            ImageUrl = "",
                            InStock = 108,
                            IsPreferredBook = true,
                            Language = "Türkçe",
                            Name = "Son Av",
                            PageNumber = "304",
                            Price = 27.36m,
                            PublicationDate = "2020",
                            Publisher = "Doğan Kitap"
                        });
                });

            modelBuilder.Entity("KitApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Edebiyat"
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Eğitim"
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Foreign Languages"
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Hobi"
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Şiir",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Roman",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Fantastik",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Polisiye",
                            ParentCategoryId = 6
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Bilim Kurgu",
                            ParentCategoryId = 6
                        });
                });

            modelBuilder.Entity("KitApp.Models.Book", b =>
                {
                    b.HasOne("KitApp.Models.Category", null)
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
